If OBJECT_ID('tempdb..#AdjustmentReasonCode') Is Not Null Drop Table #AdjustmentReasonCode
Select '00' As AdjustmentReasonCode, Cast('Prospective Payment Components' As VarChar(128)) As AdjustmentReason Into #AdjustmentReasonCode
Insert Into #AdjustmentReasonCode Select '01','Notification of Death of Beneficiary'
Insert Into #AdjustmentReasonCode Select '02','Retroactive Enrollment'
Insert Into #AdjustmentReasonCode Select '03','Retroactive Dis-enrollment'
Insert Into #AdjustmentReasonCode Select '04','Correction to Enrollment Date'
Insert Into #AdjustmentReasonCode Select '05','Correction to Dis-enrollment Date'
Insert Into #AdjustmentReasonCode Select '06','Correction to Part A Entitlement'
Insert Into #AdjustmentReasonCode Select '07','Retroactive Hospice Status'
Insert Into #AdjustmentReasonCode Select '08','Retroactive ESRD Status'
Insert Into #AdjustmentReasonCode Select '09','Retroactive Institutional Status'
Insert Into #AdjustmentReasonCode Select '10','Retroactive Medicaid Status'
Insert Into #AdjustmentReasonCode Select '11','Retroactive Change to State County Code'
Insert Into #AdjustmentReasonCode Select '12','Date of Death Correction'
Insert Into #AdjustmentReasonCode Select '13','Date of Birth Correction'
Insert Into #AdjustmentReasonCode Select '14','Correction to Sex Code'
Insert Into #AdjustmentReasonCode Select '15','Obsolete'
Insert Into #AdjustmentReasonCode Select '16','Obsolete'
Insert Into #AdjustmentReasonCode Select '17','For APPS use only'
Insert Into #AdjustmentReasonCode Select '18','Part C Rate Change'
Insert Into #AdjustmentReasonCode Select '19','Correction to Part B Entitlement'
Insert Into #AdjustmentReasonCode Select '20','Retroactive Working Aged Status'
Insert Into #AdjustmentReasonCode Select '21','Retroactive NHC Status'
Insert Into #AdjustmentReasonCode Select '22','Dis-enrolled Due to Prior ESRD'
Insert Into #AdjustmentReasonCode Select '23','Demo Factor Adjustment'
Insert Into #AdjustmentReasonCode Select '24','Obsolete'
Insert Into #AdjustmentReasonCode Select '25','Part C Risk Adjustment Factor Change/Recon'
Insert Into #AdjustmentReasonCode Select '26','Mid-year Part C Risk Adjustment Factor Change'
Insert Into #AdjustmentReasonCode Select '27','Retroactive Change to Congestive Heart Failure (CHF) Payment'
Insert Into #AdjustmentReasonCode Select '28','Retroactive Change to BIPA Part B Premium Reduction Amount'
Insert Into #AdjustmentReasonCode Select '29','Retroactive Change to Hospice Rate'
Insert Into #AdjustmentReasonCode Select '30','Retroactive Change to Basic Part D Premium'
Insert Into #AdjustmentReasonCode Select '31','Retroactive Change to Part D Low Income Status'
Insert Into #AdjustmentReasonCode Select '32','Retroactive Change to Estimated Cost-Sharing Amount'
Insert Into #AdjustmentReasonCode Select '33','Retroactive Change to Estimated Reinsurance Amount'
Insert Into #AdjustmentReasonCode Select '34','Retroactive Change Basic Part C Premium'
Insert Into #AdjustmentReasonCode Select '35','Retroactive Change to Rebate Amount'
Insert Into #AdjustmentReasonCode Select '36','Part D Rate Change'
Insert Into #AdjustmentReasonCode Select '37','Part D Risk Adjustment Factor Change'
Insert Into #AdjustmentReasonCode Select '38','Part C Segment ID Change'
Insert Into #AdjustmentReasonCode Select '41','Part D Risk Adjustment Factor Change (ongoing)'
Insert Into #AdjustmentReasonCode Select '42','Retroactive MSP Status'
Insert Into #AdjustmentReasonCode Select '44','Retroactive correction of previously failed Payment (affects Part C and D)'
Insert Into #AdjustmentReasonCode Select '45','Dis-enroll for Failure to Pay Part D IRMAA Premium – Reported for Pt C and Pt D'
Insert Into #AdjustmentReasonCode Select '46','Correction of Part D Eligibility – Reported for Pt D'
Insert Into #AdjustmentReasonCode Select '50','Payment adjustment due to Beneficiary Merge'
Insert Into #AdjustmentReasonCode Select '60','Part C Payment Adjustments created as a result of the RAS overpayment file processing'
Insert Into #AdjustmentReasonCode Select '61','Part D Payment Adjustments created as a result of the RAS overpayment file processing'
Insert Into #AdjustmentReasonCode Select '65','Confirmed Incarceration – Reported for Pt C and Pt D'
Insert Into #AdjustmentReasonCode Select '66','Not Lawfully Present'
Insert Into #AdjustmentReasonCode Select '90','System of Record History Alignment'
Insert Into #AdjustmentReasonCode Select '94','Special Payment Adjustment Due to Cleanup'

Create Index ix_AdjustmentReasonCode On #AdjustmentReasonCode(AdjustmentReasonCode)
