If OBJECT_ID('tempdb..#RAFactor') Is Not Null Drop Table #RAFactor
Select Cast('C' As Char(2)) As RAFactorTypeCode, 'Community (Adjustments before 2017; PACE only beginning 1/2017 and ending 12/2019)' As RAFactor Into #RAFactor
Insert Into #RAFactor Select 'C1', 'Community Post Graft 4-9 (ESRD)'
Insert Into #RAFactor Select 'C2', 'Community Post Graft 10+ (ESRD)'
Insert Into #RAFactor Select 'CF', 'Community Full Dual'
Insert Into #RAFactor Select 'CP', 'Community Partial Dual'
Insert Into #RAFactor Select 'CN', 'Community Non-Dual'
Insert Into #RAFactor Select 'D', 'Dialysis (ESRD)'
Insert Into #RAFactor Select 'E', 'New Enrollee'
Insert Into #RAFactor Select 'ED', 'New Enrollee Dialysis (ESRD)'
Insert Into #RAFactor Select 'E1', 'New Enrollee Post Graft 4-9 (ESRD)'
Insert Into #RAFactor Select 'E2', 'New Enrollee Post Graft 10+ (ESRD)'
Insert Into #RAFactor Select 'G1', 'Post Graft 4-9 (ESRD)'
Insert Into #RAFactor Select 'G2', 'Post Graft 10+ (ESRD)'
Insert Into #RAFactor Select 'I', 'Institutional'
Insert Into #RAFactor Select 'I1', 'Institutional Post Graft 4-9 (ESRD)'
Insert Into #RAFactor Select 'I2', 'Institutional Post Graft 10+ (ESRD)'
Insert Into #RAFactor Select 'SE', 'New Enrollee Chronic Care SNP'
Insert Into #RAFactor Select 'PA', 'PACE Dialysis Factor'
Insert Into #RAFactor Select 'PB', 'PACE New Enrollee Dialysis Factor'
Insert Into #RAFactor Select 'PC', 'PACE Community Post Graft 4-9'
Insert Into #RAFactor Select 'PD', 'PACE Institutional Post Graft 4-9'
Insert Into #RAFactor Select 'PE', 'PACE New Enrollee Post Graft 4-9'
Insert Into #RAFactor Select 'PF', 'PACE Community Post Graft 10+'
Insert Into #RAFactor Select 'PG', 'PACE Institutional Post Graft 10+' 
Insert Into #RAFactor Select 'PH', 'PACE New Enrollee Post Graft 10+'
Insert Into #RAFactor Select 'PI', 'PACE Community Full Dual'
Insert Into #RAFactor Select 'PJ', 'PACE Community Partial Dual'
Insert Into #RAFactor Select 'PK', 'PACE Community Non-Dual'
Insert Into #RAFactor Select 'PL', 'PACE Post Graft 1'
Insert Into #RAFactor Select 'PM', 'PACE Post Graft 2-3'

Create Index ix_RAFactorTypeCode On #RAFactor(RAFactorTypeCode)
